export const newslist = [
	`local Alec doesn't wear flannel, global population baffled`,
	`local man loses snapchat steak of 4 days, steals the constituition`,
	`local Middle School Bridges Confessions called a cyberbully by Kerinius Borzellius, but none of the "victims" agree`,
	`local shoe gets thrown at fundraiser guy, all students agree it was justified`,
	`local PSAT app turns man into a smurf`,
	`local Something Rotten is a smashing success!`,
	`local Addams Family is a smashing success!`,
	`local iceberg makes a school panic`,
	`local student goes to Boulder, Colorado, meets Dr. Nefario`,
	`local student watches grass grow, paint dries instead`,
	`local Theodore codes for BridgesHOF.com, goes insane`,
	`local local goes local, localed by local`,
	`local short film gets made, experts confused`,
	`local man watches Cooking With Alec, hospitalized`,
	`local Mark Long gets called Marcus Length, students outraged`,
	`I CALLED MARK LONG AT 3AM (GONE WRONG) (COPS CALLED) 😲😲😲`,
	`I AM AN OPTIMUS PRIME EARTHER. THE EARTH IS SHAPED LIKE OPTIMUS PRIME, AND IT IS TRUE. YOU CANNOT DENY IT.`,
	`the Scottius Swickius of The Bridgium Acadimium has been notified about your Alec buisness`,
	`Researchers provide evidence that Christopher Laurence is more powerful than God, Jod, Thor, Zeus, Allah, and Buddha, all combined`,
	`PERRY THE SCHLOGGINATOR IS AT MY HOUSE! HE'S COMING FOR ME!!!`,
	`Rooms? I was rooms once. They crazied me in a lock. A rats lock. A rats locked full of crazy, and crazy makes me rooms.`,
	`im running out of things to put here`,
	`Mr. Long I don't feel so good`,
	`heeeelp! help me!`,
	`tal got a LOWWWWW TAPEERRRR FADEEE`,
	`"bro Gru is so mean. i married the moon and then THE MFER STOLE IT! DIABOLICAL!" says Fester in an interview`,
];